import torch

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
SEED = 42
HIDDEN_DIM = 128
MESSAGE_PASSING_STEPS = 3

NUM_HEADS = 6
DROPOUT = 0.1

ATTENTION_SCALE = 1.0
FFN_HIDDEN_DIM = 256
FFN_LAYERS = 2

USE_ADJACENCY_MATRIX = True
USE_DISTANCE_MATRIX = True
USE_COULOMB_MATRIX = True

Z_SCORE_NORMALIZATION = True

MAX_ATOMS = 100
SMILES_COLUMN = "smiles"
